// Generated by gencpp from file circle_msgs/Circle.msg
// DO NOT EDIT!


#ifndef CIRCLE_MSGS_MESSAGE_CIRCLE_H
#define CIRCLE_MSGS_MESSAGE_CIRCLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace circle_msgs
{
template <class ContainerAllocator>
struct Circle_
{
  typedef Circle_<ContainerAllocator> Type;

  Circle_()
    : header()
    , center()
    , radius(0.0)  {
    }
  Circle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , center(_alloc)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::circle_msgs::Circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::circle_msgs::Circle_<ContainerAllocator> const> ConstPtr;

}; // struct Circle_

typedef ::circle_msgs::Circle_<std::allocator<void> > Circle;

typedef boost::shared_ptr< ::circle_msgs::Circle > CirclePtr;
typedef boost::shared_ptr< ::circle_msgs::Circle const> CircleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::circle_msgs::Circle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::circle_msgs::Circle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::circle_msgs::Circle_<ContainerAllocator1> & lhs, const ::circle_msgs::Circle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.center == rhs.center &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::circle_msgs::Circle_<ContainerAllocator1> & lhs, const ::circle_msgs::Circle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace circle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::circle_msgs::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::circle_msgs::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::circle_msgs::Circle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::circle_msgs::Circle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::circle_msgs::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::circle_msgs::Circle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::circle_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ec3f1e4c9ed653d64f4a72bda22768b";
  }

  static const char* value(const ::circle_msgs::Circle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ec3f1e4c9ed653dULL;
  static const uint64_t static_value2 = 0x64f4a72bda22768bULL;
};

template<class ContainerAllocator>
struct DataType< ::circle_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "circle_msgs/Circle";
  }

  static const char* value(const ::circle_msgs::Circle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::circle_msgs::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point center\n"
"float64 radius\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::circle_msgs::Circle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::circle_msgs::Circle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.center);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Circle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::circle_msgs::Circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::circle_msgs::Circle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CIRCLE_MSGS_MESSAGE_CIRCLE_H
