// Generated by gencpp from file circle_msgs/CircleArray.msg
// DO NOT EDIT!


#ifndef CIRCLE_MSGS_MESSAGE_CIRCLEARRAY_H
#define CIRCLE_MSGS_MESSAGE_CIRCLEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <circle_msgs/Circle.h>

namespace circle_msgs
{
template <class ContainerAllocator>
struct CircleArray_
{
  typedef CircleArray_<ContainerAllocator> Type;

  CircleArray_()
    : header()
    , circles()  {
    }
  CircleArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , circles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::circle_msgs::Circle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::circle_msgs::Circle_<ContainerAllocator> >::other >  _circles_type;
  _circles_type circles;





  typedef boost::shared_ptr< ::circle_msgs::CircleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::circle_msgs::CircleArray_<ContainerAllocator> const> ConstPtr;

}; // struct CircleArray_

typedef ::circle_msgs::CircleArray_<std::allocator<void> > CircleArray;

typedef boost::shared_ptr< ::circle_msgs::CircleArray > CircleArrayPtr;
typedef boost::shared_ptr< ::circle_msgs::CircleArray const> CircleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::circle_msgs::CircleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::circle_msgs::CircleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::circle_msgs::CircleArray_<ContainerAllocator1> & lhs, const ::circle_msgs::CircleArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.circles == rhs.circles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::circle_msgs::CircleArray_<ContainerAllocator1> & lhs, const ::circle_msgs::CircleArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace circle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::circle_msgs::CircleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::circle_msgs::CircleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::circle_msgs::CircleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::circle_msgs::CircleArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::circle_msgs::CircleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::circle_msgs::CircleArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::circle_msgs::CircleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f6edfcd6124c497c196e136cc24f493";
  }

  static const char* value(const ::circle_msgs::CircleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f6edfcd6124c497ULL;
  static const uint64_t static_value2 = 0xc196e136cc24f493ULL;
};

template<class ContainerAllocator>
struct DataType< ::circle_msgs::CircleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "circle_msgs/CircleArray";
  }

  static const char* value(const ::circle_msgs::CircleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::circle_msgs::CircleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"circle_msgs/Circle[] circles\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: circle_msgs/Circle\n"
"Header header\n"
"geometry_msgs/Point center\n"
"float64 radius\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::circle_msgs::CircleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::circle_msgs::CircleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.circles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::circle_msgs::CircleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::circle_msgs::CircleArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "circles[]" << std::endl;
    for (size_t i = 0; i < v.circles.size(); ++i)
    {
      s << indent << "  circles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::circle_msgs::Circle_<ContainerAllocator> >::stream(s, indent + "    ", v.circles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CIRCLE_MSGS_MESSAGE_CIRCLEARRAY_H
