// Generated by gencpp from file line_msgs/LineArray.msg
// DO NOT EDIT!


#ifndef LINE_MSGS_MESSAGE_LINEARRAY_H
#define LINE_MSGS_MESSAGE_LINEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <line_msgs/Line.h>

namespace line_msgs
{
template <class ContainerAllocator>
struct LineArray_
{
  typedef LineArray_<ContainerAllocator> Type;

  LineArray_()
    : header()
    , lines()  {
    }
  LineArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::line_msgs::Line_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::line_msgs::Line_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;





  typedef boost::shared_ptr< ::line_msgs::LineArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_msgs::LineArray_<ContainerAllocator> const> ConstPtr;

}; // struct LineArray_

typedef ::line_msgs::LineArray_<std::allocator<void> > LineArray;

typedef boost::shared_ptr< ::line_msgs::LineArray > LineArrayPtr;
typedef boost::shared_ptr< ::line_msgs::LineArray const> LineArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_msgs::LineArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_msgs::LineArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_msgs::LineArray_<ContainerAllocator1> & lhs, const ::line_msgs::LineArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lines == rhs.lines;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_msgs::LineArray_<ContainerAllocator1> & lhs, const ::line_msgs::LineArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::line_msgs::LineArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_msgs::LineArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msgs::LineArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msgs::LineArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msgs::LineArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msgs::LineArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_msgs::LineArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67b24130203bbd6fa25f7fed2d1b50b9";
  }

  static const char* value(const ::line_msgs::LineArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67b24130203bbd6fULL;
  static const uint64_t static_value2 = 0xa25f7fed2d1b50b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_msgs::LineArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_msgs/LineArray";
  }

  static const char* value(const ::line_msgs::LineArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_msgs::LineArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"line_msgs/Line[] lines\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: line_msgs/Line\n"
"Header header\n"
"geometry_msgs/Point first\n"
"geometry_msgs/Point second\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::line_msgs::LineArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_msgs::LineArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_msgs::LineArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_msgs::LineArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::line_msgs::Line_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_MSGS_MESSAGE_LINEARRAY_H
