// Generated by gencpp from file line_msgs/Line.msg
// DO NOT EDIT!


#ifndef LINE_MSGS_MESSAGE_LINE_H
#define LINE_MSGS_MESSAGE_LINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace line_msgs
{
template <class ContainerAllocator>
struct Line_
{
  typedef Line_<ContainerAllocator> Type;

  Line_()
    : header()
    , first()
    , second()  {
    }
  Line_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , first(_alloc)
    , second(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _first_type;
  _first_type first;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _second_type;
  _second_type second;





  typedef boost::shared_ptr< ::line_msgs::Line_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_msgs::Line_<ContainerAllocator> const> ConstPtr;

}; // struct Line_

typedef ::line_msgs::Line_<std::allocator<void> > Line;

typedef boost::shared_ptr< ::line_msgs::Line > LinePtr;
typedef boost::shared_ptr< ::line_msgs::Line const> LineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_msgs::Line_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_msgs::Line_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_msgs::Line_<ContainerAllocator1> & lhs, const ::line_msgs::Line_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.first == rhs.first &&
    lhs.second == rhs.second;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_msgs::Line_<ContainerAllocator1> & lhs, const ::line_msgs::Line_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::line_msgs::Line_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_msgs::Line_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msgs::Line_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msgs::Line_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msgs::Line_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msgs::Line_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_msgs::Line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "311c7725c0a082e091be9312cb146234";
  }

  static const char* value(const ::line_msgs::Line_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x311c7725c0a082e0ULL;
  static const uint64_t static_value2 = 0x91be9312cb146234ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_msgs::Line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_msgs/Line";
  }

  static const char* value(const ::line_msgs::Line_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_msgs::Line_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point first\n"
"geometry_msgs/Point second\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::line_msgs::Line_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_msgs::Line_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Line_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_msgs::Line_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_msgs::Line_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "first: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_MSGS_MESSAGE_LINE_H
